import { ref } from "vue";

export const newEmployee =ref({
    name:'',
    lastName:'',
    address:'',
    dni:'',
    email:'',
    dob:'',
    studies:1,
    cuil:'',
    phoneNumber:'',
    employeeRecord:'',
    category:0,
    functionEmployee:'',
    basicSalary:'',
    seniority:'',
    startDate:'',
    startDateCategory:'',
    cbu:'',
    bank:'',
    mudon:false,
    upcn:false,
    muoem:false,
    politicalContribution:false,
    affiliationUoem:false,
    remunerative:false,
})